### ISSUE TITLE
Moving Patch to Bank overwrites patches in bank

### ISSUE THREAD

**Issue by personalnadir** [meanmedianmoge/zoia_lib#95]
**Describe the bug**
I have a bank with 60 patches. When I load it and move a new patch to it, the new patch replaces the patch in position 32, instead of being added to an empty slot at the end.

**To Reproduce**
1. In banks tab. Load bank with more than 32 patches
2. Select new patch to add and click Move patch to bank button
3. The new patch will overwrite patch 32

**Expected behavior**
New patch is added to the first empty slot in bank if one exists.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.1

** The Bank JSON Content is **
```
[
  {
    "slot": 0,
    "id": "138026"
  },
  {
    "slot": 32,
    "id": "132569"
  },
  {
    "slot": 1,
    "id": "134630_v1"
  },
  {
    "slot": 33,
    "id": "129995"
  },
  {
    "slot": 2,
    "id": "137942"
  },
  {
    "slot": 34,
    "id": "107526"
  },
  {
    "slot": 3,
    "id": "130506"
  },
  {
    "slot": 35,
    "id": "134612"
  },
  {
    "slot": 4,
    "id": "134984"
  },
  {
    "slot": 36,
    "id": "130040_v1"
  },
  {
    "slot": 5,
    "id": "138000"
  },
  {
    "slot": 37,
    "id": "130040_v2"
  },
  {
    "slot": 6,
    "id": "135748"
  },
  {
    "slot": 38,
    "id": "124605_v1"
  },
  {
    "slot": 7,
    "id": "107523"
  },
  {
    "slot": 39,
    "id": "124605_v2"
  },
  {
    "slot": 8,
    "id": "130693"
  },
  {
    "slot": 40,
    "id": "115749"
  },
  {
    "slot": 9,
    "id": "107529"
  },
  {
    "slot": 41,
    "id": "123771"
  },
  {
    "slot": 10,
    "id": "106247"
  },
  {
    "slot": 42,
    "id": "129199"
  },
  {
    "slot": 11,
    "id": "129828"
  },
  {
    "slot": 43,
    "id": "131138"
  },
  {
    "slot": 12,
    "id": "128799"
  },
  {
    "slot": 44,
    "id": "129202"
  },
  {
    "slot": 13,
    "id": "127726"
  },
  {
    "slot": 45,
    "id": "127609"
  },
  {
    "slot": 14,
    "id": "123495"
  },
  {
    "slot": 46,
    "id": "122856_v1"
  },
  {
    "slot": 15,
    "id": "123487"
  },
  {
    "slot": 47,
    "id": "122856_v2"
  },
  {
    "slot": 16,
    "id": "106178"
  },
  {
    "slot": 48,
    "id": "107142"
  },
  {
    "slot": 17,
    "id": "106181"
  },
  {
    "slot": 49,
    "id": "113614"
  },
  {
    "slot": 18,
    "id": "106772"
  },
  {
    "slot": 50,
    "id": "129671"
  },
  {
    "slot": 19,
    "id": "106407"
  },
  {
    "slot": 51,
    "id": "107970"
  },
  {
    "slot": 20,
    "id": "108062"
  },
  {
    "slot": 52,
    "id": "134666"
  },
  {
    "slot": 21,
    "id": "123487"
  },
  {
    "slot": 53,
    "id": "109920"
  },
  {
    "slot": 22,
    "id": "123495"
  },
  {
    "slot": 54,
    "id": "123408"
  },
  {
    "slot": 23,
    "id": "107166"
  },
  {
    "slot": 55,
    "id": "137846"
  },
  {
    "slot": 24,
    "id": "122008"
  },
  {
    "slot": 56,
    "id": "125709"
  },
  {
    "slot": 25,
    "id": "131958"
  },
  {
    "slot": 57,
    "id": "107513"
  },
  {
    "slot": 26,
    "id": "106993"
  },
  {
    "slot": 58,
    "id": "112261"
  },
  {
    "slot": 27,
    "id": "119778_v1"
  },
  {
    "slot": 59,
    "id": "124933"
  },
  {
    "slot": 28,
    "id": "119778_v2"
  },
  {
    "slot": 29,
    "id": "119778_v3"
  },
  {
    "slot": 30,
    "id": "119778_v4"
  },
  {
    "slot": 31,
    "id": "119778_v5"
  }
]
```

**Comment by meanmedianmoge** [comment]
Confirmed, working on it. Thanks for catching this!

**Comment by meanmedianmoge** [comment]
Issue has been resolved. Feel free to comment back if it persists.

**Comment by personalnadir** [comment]
Thanks for looking into this, however I'm still seeing the issue occur. Lines 470 - 473 in ZOIALibrarian_bank.py assume that data_banks is sorted by slot, but this is never enforced by the code from what I can see. If you look at the bank I provided the last slot id is 31, but the array is not sorted by slot number - the object at index 1 has slot number 32 for instance. 

I think that sorting the json data by slot would enforce this. 

Something like the following (not tested) could also find the first empty space in banks where there are gaps:
```
        if self.data_banks:
            occupied = [False] * 64
            for pch in self.data_banks:
                oppupied[pch["slot"]] = True
            drop_index = occupied.index(False)
````

**Comment by meanmedianmoge** [comment]
Much appreciated, that snippet comes in handy! Should be resolved as of 265244f (I sort the list before the open slot is identified).

**Comment by personalnadir** [comment]
Fantastic, that is working for me now

**Comment by personalnadir** [comment]
I just checked, the index function throws a ValueError if the value is not in list. You'll either need to try/except or test before you call it
```
      if self.data_banks:
            occupied = [False] * 64
            for pch in self.data_banks:
                oppupied[pch["slot"]] = True
            try:
                 drop_index = occupied.index(False)
            except ValueError:
                 drop_index = 64 <-- -1 would be clearer, but this should work with the check later on

            ------

            if False in occupied:
                 drop_index = occupied.index(False)
           else:
                drop_index = 64
````

**Comment by meanmedianmoge** [comment]
Good catch. At that point, the bank is full anyway so it'd be easier to raise an error similar to the Local Storage export function (you pick a slot and it confirms if you'd like to overwrite the patches that exist there).

**Comment by meanmedianmoge** [comment]
Ok all set. @personalnadir can you take a look to see if the new functionality works for you? Thanks for your help!

**Comment by personalnadir** [comment]
That works, no errors for me. Not sure about the pop up message; part of it reads: "Note that if you're moving a version history, multiple patches will be overwritten." The rest of the message made sense, but that bit was confusing.

**Comment by meanmedianmoge** [comment]
A version history contains multiple patches. So if you click or drag one over to the bank, it will overwrite to make room, starting with the slot you chose and ending at slot + len(version history)-1. This pop-up is just to confirm that the user is aware of the process.
